### ISSUE TITLE
Error while adding task 

### ISSUE THREAD

**Issue by gem874** [CorpGlory/grafana-data-exporter-panel#37]
Hello, I have questions. 
When I export data using your library, I can't do that. 
===================================
I installed follows.
1. Set grafana-data-exporter 
1-1. Create api key in grafana (Viewer) 
1-2. Download your library in local system
1-3. Extract tar and then modify config.json file 
1-4. Run node Server - It work fine. When I access 8000 port I will see this message. 
"Grafana-data-exporter server works"

2. simple-json-datasource
2-1. Install simple-json-datasource and then restart grafana server
2-2. Go to datasources/new page and then create SimpleJson type datasource 
- backend url is <my grafana>:8000

3.  Step3. grafana-data-exporter-panel
3-1. Download your library in my grafana plugins path 
3-2. Extract tar and then restart grafana server 
- I can see data-exporter-panel ui successfully. 

4. Step4. Import your sample dashboard template
4-1. Copy your json template file
4-2. Import template to grafana graph
- I can see ui 

===================================
After I installed these process, I try to export data but I can't. 
* Dashboard Setting :  Back end_URL : localhost:8000 
* Error Messages 
1. data panel : Cannot read property 'length' of undefined
2. Process panel : Request Error
3. When I export, I see the "error while adding task" 
===================================
Sample Error in data panel. . . 
> TypeError: Cannot read property 'length' of undefined
    at http://{domain}/public/build/app.dfabdd44b3be44288eac.js:22:557392
    at Jt (http://{domain}/public/build/vendor.dfabdd44b3be44288eac.js:9:5512)
    at Function.fr.filter (http://{domain}/public/build/vendor.dfabdd44b3be44288eac.js:9:50982)
    at t.query (http://{domain}/public/build/app.dfabdd44b3be44288eac.js:22:557246)
    at e.issueQueries (http://{domain}/public/build/app.dfabdd44b3be44288eac.js:22:485671)
    at http://{domain}/public/build/app.dfabdd44b3be44288eac.js:22:872775
    at http://{domain}/public/build/vendor.dfabdd44b3be44288eac.js:130:92198
    at http://{domain}/public/build/vendor.dfabdd44b3be44288eac.js:130:92295
    at l.$digest (http://{domain}/public/build/vendor.dfabdd44b3be44288eac.js:130:97589)
    at http://{domain}/public/build/vendor.dfabdd44b3be44288eac.js:130:99404

**Comment by rozetko** [comment]
Hi @gem874,

Thank you for contributing the issue.

Please provide the following info:
- Which exporter version are you using?
- Which Grafana version are you using?
- Are there any errors in the exporter server?
- Which datasource are you trying to export data from? e.g. InfluxDB / Prometheus / etc

**Comment by vishwakhrushi** [comment]
I have a similar error, below are the details for the components I'm using.

Grafana-exporter-version: v0.5.1
Grafana-version: v7.1.5
datasource: Prometheus

Below is the error log grafana-data-exporter 

>  0 day: 1611858600000ms -> 1611945000000ms                                                                                 
│ (node:25) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
│     at /var/www/dist/server.js:59057:44                                                                                   
│     at Array.map (<anonymous>)                                                                                            
│     at PrometheusMetric.getResults (/var/www/dist/server.js:59053:20)                                                     
│     at Object.<anonymous> (/var/www/dist/server.js:32429:44)                                                              
│     at Generator.next (<anonymous>)                                                                                       
│     at fulfilled (/var/www/dist/server.js:32376:58)                                                                       
│     at runMicrotasks (<anonymous>)                                                                                        
│     at processTicksAndRejections (internal/process/task_queues.js:93:5)                                                   (node:25) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:25) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
